// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import markdoc from '@astrojs/markdoc';

// https://astro.build/config
export default defineConfig({
  integrations: [
    markdoc(),
    starlight({
      title: {
        en: 'StacksPay',
        'pt-BR': 'StacksPay'
      },
      defaultLocale: 'en',
      locales: {
        en: {
          label: 'English',
        },
        'pt-BR': {
          label: 'Português (Brasil)',
        },
        // 'es': {
        //   label: 'Español',
        //   dir: 'ltr',
        // },
        // 'fr': {
        //   label: 'Français',
        //   dir: 'ltr',
        // },
        // de: {
        //   label: 'Deutsch',
        //   dir: 'ltr',
        // },
        // 'pt': {
        //   label: 'Português',
        //   dir: 'ltr',
        // },
        // 'jp': {
        //   label: '日本語',
        //   dir: 'ltr',
        // },
        // 'ko': {
        //   label: '한국어',
        // },
        // 'zh': {
        //   label: '中文',
        // },
        // 'zh-tw': {
        //   label: '繁體中文',
        // },
      },
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/dantrevino/stackspay.org',
        },
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/dantrevino/stackspay-js',
        },
        {
          icon: 'discord',
          label: 'Discord',
          href: 'https://discord.gg/pHQvtJU7Jc',
        },
      ],
      sidebar: [
        {
          label: 'Getting Started',
          translations: {
            en: 'Getting Started',
            'pt-BR': 'Introdução',
            // es: 'Comenzando',
            // fr: 'Commencer',
            // de: 'Erste Schritte',
            // pt: 'Começando',
            // jp: 'はじめに',
            // ko: '시작하기',
            // zh: '开始使用',
            // 'zh-tw': '開始使用',
          },
          items: [
            {
              label: 'What is StacksPay?',
              slug: 'introduction',
              translations: {
                en: 'What is StacksPay?',
                'pt-BR': 'O que é StacksPay?',
                // es: '¿Qué es StacksPay?',
                // fr: 'Qu’est-ce que StacksPay ?',
                // de: 'Was ist StacksPay?',
                // pt: 'O que é StacksPay?',
                // jp: 'StacksPayとは？',
                // ko: 'StacksPay란 무엇인가요?',
                // zh: '什么是StacksPay？',
                // 'zh-tw': '什麼是StacksPay？',
              },
            },
            {
              label: 'Quick Start',
              slug: 'quick-start',
              translations: {
                en: 'Quick Start',
                'pt-BR': 'Começando Rápido',
                // es: 'Comenzando Rápido',
                // fr: 'Démarrage Rapide',
                // de: 'Schnellstart',
                // pt: 'Começando Rápido',
                // jp: 'クイックスタート',
                // ko: '빠른 시작',
                // zh: '快速开始',
                // 'zh-tw': '快速開始',
              }
            },
            {
              label: 'Why StacksPay?',
              slug: 'why-stackspay',
              translations: {
                en: 'Why StacksPay?',
                'pt-BR': 'Por que StacksPay?',
                // es: '¿Por qué StacksPay?',
                // fr: 'Pourquoi StacksPay ?',
                // de: 'Warum StacksPay?',
                // pt: 'Por que StacksPay?',
                // jp: 'StacksPayの理由',
                // ko: 'StacksPay의 이유',
                // zh: '为什么选择StacksPay？',
                // 'zh-tw': '為什麼選擇StacksPay？',
              }
            }
          ],
        },
        {
          label: 'For Users',
          translations: {
            en: 'For Users',
            'pt-BR': 'Para Usuários',
            // es: 'Para Usuarios',
            // fr: 'Pour les Utilisateurs',
            // de: 'Für Benutzer',
            // pt: 'Para Usuários',
            // jp: 'ユーザー向け',
            // ko: '사용자를 위한',
            // zh: '面向用户',
            // 'zh-tw': '面向使用者',
          },
          items: [
            {
              label: 'Making Payments',
              slug: 'users/making-payments',
              translations: {
                en: 'Making Payments',
                'pt-BR': 'Fazendo Pagamentos',
                // es: 'Haciendo Pagos',
                // fr: 'Effectuer des Paiements',
                // de: 'Zahlungen Tätigen',
                // pt: 'Fazendo Pagamentos',
                // jp: '支払いの実行',
                // ko: '지불하기',
                // zh: '进行支付',
                // 'zh-tw': '進行支付',
              },
            },
            {
              label: 'Supported Wallets & Apps',
              slug: 'users/supported-wallets',
              translations: {
                en: 'Supported Wallets & Apps',
                'pt-BR': 'Carteiras e Aplicativos Suportados',
                // es: 'Carteras y Aplicaciones Soportadas',
                // fr: 'Portefeuilles et Applications Supportés',
                // de: 'Unterstützte Wallets & Apps',
                // pt: 'Carteiras e Aplicativos Suportados',
                // jp: 'サポートされているウォレットとアプリ',
                // ko: '지원되는 지갑 및 앱',
                // zh: '支持的钱包和应用',
                // 'zh-tw': '支持的錢包和應用',
              },
            },
            {
              label: 'Security & Safety',
              slug: 'users/security',
              translations: {
                en: 'Security & Safety',
                'pt-BR': 'Segurança e Proteção',
                // es: 'Seguridad y Protección',
                // fr: 'Sécurité et Protection',
                // de: 'Sicherheit und Schutz',
                // pt: 'Segurança e Proteção',
                // jp: 'セキュリティと安全',
                // ko: '보안 및 안전',
                // zh: '安全与保障',
                // 'zh-tw': '安全與保障',
              },
            },
            {
              label: 'Troubleshooting',
              slug: 'users/troubleshooting',
              translations: {
                en: 'Troubleshooting',
                'pt-BR': 'Solução de Problemas',
                // es: 'Solución de Problemas',
                // fr: 'Dépannage',
                // de: 'Fehlerbehebung',
                // pt: 'Solução de Problemas',
                // jp: 'トラブルシューティング',
                // ko: '문제 해결',
                // zh: '故障排除',
                // 'zh-tw': '故障排除',
              },
            },
          ],
        },
        {
          label: 'For Merchants',
          translations: {
            en: 'For Merchants',
            'pt-BR': 'Para Comerciantes',
            // es: 'Para Comerciantes',
            // fr: 'Pour les Commerçants',
            // de: 'Für Händler',
            // pt: 'Para Comerciantes',
            // jp: '商人向け',
            // ko: '상인을 위한',
            // zh: '面向商家',
            // 'zh-tw': '面向商家',
          },
          items: [
            {
              label: 'Getting Started',
              slug: 'merchants/getting-started',
              translations: {
                en: 'Getting Started',
                'pt-BR': 'Introdução',
                // es: 'Introducción',
                // fr: 'Commencer',
                // de: 'Erste Schritte',
                // pt: 'Introdução',
                // jp: 'はじめに',
                // ko: '시작하기',
                // zh: '开始',
                // 'zh-tw': '開始',
              },
            },
            {
              label: 'Accepting Payments',
              slug: 'merchants/accepting-payments',
              translations: {
                en: 'Accepting Payments',
                'pt-BR': 'Aceitando Pagamentos',
                // es: 'Aceptando Pagos',
                // fr: 'Accepter des Paiements',
                // de: 'Zahlungen Akzeptieren',
                // pt: 'Aceitando Pagamentos',
                // jp: '支払いの受け入れ',
                // ko: '지불 수락',
                // zh: '接受支付',
                // 'zh-tw': '接受支付',
              },
            },
            {
              label: 'Payment Flow',
              slug: 'merchants/payment-flow',
              translations: {
                en: 'Payment Flow',
                'pt-BR': 'Fluxo de Pagamento',
                // es: 'Flujo de Pagos',
                // fr: 'Flux de Paiement',
                // de: 'Zahlungsfluss',
                // pt: 'Fluxo de Pagamento',
                // jp: '支払いフロー',
                // ko: '지불 흐름',
                // zh: '支付流程',
                // 'zh-tw': '支付流程',
              },
            },
            {
              label: 'Order Management',
              slug: 'merchants/order-management',
              translations: {
                en: 'Order Management',
                'pt-BR': 'Gerenciamento de Pedidos',
                // es: 'Gestión de Pedidos',
                // fr: 'Gestion des Commandes',
                // de: 'Bestellverwaltung',
                // pt: 'Gerenciamento de Pedidos',
                // jp: '注文管理',
                // ko: '주문 관리',
                // zh: '订单管理',
                // 'zh-tw': '訂單管理',
              },
            },
            {
              label: 'Business Benefits',
              slug: 'merchants/business-benefits',
              translations: {
                en: 'Business Benefits',
                'pt-BR': 'Benefícios para os Negócios',
                // es: 'Beneficios para los Negocios',
                // fr: 'Avantages pour les Entreprises',
                // de: 'Geschäftsvorteile',
                // pt: 'Benefícios para os Negócios',
                // jp: 'ビジネスの利点',
                // ko: '비즈니스 이점',
                // zh: '商业利益',
                // 'zh-tw': '商業利益',
              },
            }
          ],
        },
        {
          label: 'For Developers',
          translations: {
            en: 'For Developers',
            'pt-BR': 'Para Desenvolvedores',
            // es: 'Para Desarrolladores',
            // fr: 'Pour les Développeurs',
            // de: 'Für Entwickler',
            // pt: 'Para Desenvolvedores',
            // jp: '開発者向け',
            // ko: '개발자를 위한',
            // zh: '面向开发者',
            // 'zh-tw': '面向開發者',
          },
          items: [
            {
              label: 'Quick Start',
              slug: 'developers/quick-start',
              translations: {
                en: 'Quick Start',
                'pt-BR': 'Começando Rápido',
                // es: 'Comenzando Rápido',
                // fr: 'Démarrage Rapide',
                // de: 'Schnellstart',
                // pt: 'Começando Rápido',
                // jp: 'クイックスタート',
                // ko: '빠른 시작',
                // zh: '快速开始',
                // 'zh-tw': '快速開始',
              }
            },
            {
              label: 'API Reference',
              slug: 'developers/api-reference',
              translations: {
                en: 'API Reference',
                'pt-BR': 'Referência da API',
                // es: 'Referencia de la API',
                // fr: 'Référence de l\'API',
                // de: 'API-Referenz',
                // pt: 'Referência da API',
                // jp: 'APIリファレンス',
                // ko: 'API 참조',
                // zh: 'API参考',
                // 'zh-tw': 'API參考',
              }
            },
            {
              label: 'SDK Documentation',
              slug: 'developers/sdk',
              translations: {
                en: 'SDK Documentation',
                'pt-BR': 'Documentação do SDK',
                // es: 'Documentación del SDK',
                // fr: 'Documentation du SDK',
                // de: 'SDK-Dokumentation',
                // pt: 'Documentação do SDK',
                // jp: 'SDKドキュメント',
                // ko: 'SDK 문서',
                // zh: 'SDK文档',
                // 'zh-tw': 'SDK文檔',
              }
            },
            {
              label: 'Integration Examples',
              slug: 'developers/examples',
              translations: {
                en: 'Integration Examples',
                'pt-BR': 'Exemplos de Integração',
                // es: 'Ejemplos de Integración',
                // fr: 'Exemples d\'Intégration',
                // de: 'Integrationsbeispiele',
                // pt: 'Exemplos de Integração',
                // jp: '統合例',
                // ko: '통합 예제',
                // zh: '集成示例',
                // 'zh-tw': '整合範例',
              }
            },
            {
              label: 'Testing & Debugging',
              slug: 'developers/testing',
              translations: {
                en: 'Testing & Debugging',
                'pt-BR': 'Testes e Depuração',
                // es: 'Pruebas y Depuración',
                // fr: 'Tests et Débogage',
                // de: 'Testen und Debuggen',
                // pt: 'Testes e Depuração',
                // jp: 'テストとデバッグ',
                // ko: '테스트 및 디버깅',
                // zh: '测试与调试',
                // 'zh-tw': '測試與除錯',
              }
            },
            {
              label: 'Specification',
              slug: 'developers/specification',
              translations: {
                en: 'Specification',
                'pt-BR': 'Especificação',
                // es: 'Especificación',
                // fr: 'Spécification',
                // de: 'Spezifikation',
                // pt: 'Especificação',
                // jp: '仕様',
                // ko: '사양',
                // zh: '规范',
                // 'zh-tw': '規範',
              }
            },
          ],
        },
        {
          label: 'Technical Specification',
          translations: {
            en: 'Technical Specification',
            'pt-BR': 'Especificação Técnica',
            // es: 'Especificación Técnica',
            // fr: 'Spécification Technique',
            // de: 'Technische Spezifikation',
            // pt: 'Especificação Técnica',
            // jp: '技術仕様',
            // ko: '기술 사양',
            // zh: '技术规范',
            // 'zh-tw': '技術規範',
          },
          items: [
            { label: 'Protocol Overview', slug: 'spec/protocol', translations: { en: 'Protocol Overview', 'pt-BR': 'Visão Geral do Protocolo' } },
            { label: 'Message Format', slug: 'spec/message-format', translations: { en: 'Message Format', 'pt-BR': 'Formato da Mensagem' } },
            { label: 'URI Scheme', slug: 'spec/uri-scheme', translations: { en: 'URI Scheme', 'pt-BR': 'Esquema de URI' } },
            { label: 'Security Model', slug: 'spec/security', translations: { en: 'Security Model', 'pt-BR': 'Modelo de Segurança' } },
            { label: 'Implementation Notes', slug: 'spec/implementation', translations: { en: 'Implementation Notes', 'pt-BR': 'Notas de Implementação' } },
          ],
        },
        {
          label: 'Resources',
          translations: {
            en: 'Resources',
            'pt-BR': 'Recursos',
            // es: 'Recursos',
            // fr: 'Ressources',
            // de: 'Ressourcen',
            // pt: 'Recursos',
            // jp: 'リソース',
            // ko: '리소스',
            // zh: '资源',
            // 'zh-tw': '資源',
          },
          items: [
            { label: 'FAQ', slug: 'resources/faq', translations: { en: 'FAQ', 'pt-BR': 'Perguntas Frequentes' } },
            { label: 'Tools & Libraries', slug: 'resources/tools', translations: { en: 'Tools & Libraries', 'pt-BR': 'Ferramentas e Bibliotecas' } },
            { label: 'Community', slug: 'resources/community', translations: { en: 'Community', 'pt-BR': 'Comunidade' } },
            { label: 'Roadmap', slug: 'resources/roadmap', translations: { en: 'Roadmap', 'pt-BR': 'Roteiro' } },
          ],
        },
      ],
    }),
  ],
});
